# Generated by Django 5.2.7 on 2026-02-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='language_name',
            new_name='language',
        ),
    ]
